name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install shfmt
        run: |
          curl -L https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64 -o /tmp/shfmt
          chmod +x /tmp/shfmt
          sudo mv /tmp/shfmt /usr/local/bin/shfmt
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

